export const constants = {
	UPDATE_DEFAULT_VALUE: 'UPDATE_DEFAULT_VALUE',
	UPDATE_PAY_META: 'UPDATE_PAY_META',
	UPDATE_ARCHIVE_ACTIVITY_META: 'UPDATE_ARCHIVE_ACTIVITY_META',
	UPDATE_DEFAULT_VALUE_MODIFIERS: 'UPDATE_DEFAULT_VALUE_MODIFIERS',
	UPDATE_CURRENCY: 'UPDATE_CURRENCY',
	UPDATE_ARCHIVE_ACTIVITIES_META: 'UPDATE_ARCHIVE_ACTIVITIES_META',
	UPDATE_COMPLETION_LEVEL_VALUES: 'UPDATE_COMPLETION_LEVEL_VALUES',
	UPDATE_INTERVENTION_LEVEL_VALUES: 'UPDATE_INTERVENTION_LEVEL_VALUES',

	ADD_PUBLIC_HOLIDAYS: 'ADD_PUBLIC_HOLIDAYS',
	UPDATE_PUBLIC_HOLIDAYS: 'UPDATE_PUBLIC_HOLIDAYS',
	// IMPORT_PUBLIC_HOLIDAYS: 'IMPORT_PUBLIC_HOLIDAYS',
	ADD_SCHOOL_TERM: 'ADD_SCHOOL_TERM',
	UPDATE_SCHOOL_TERM: 'UPDATE_SCHOOL_TERM',
	ADD_USER_TO_SCHOOL_TERM: 'ADD_USER_TO_SCHOOL_TERM',
	// IMPORT_SCHOOL_TERMS: 'IMPORT_SCHOOL_TERMS',

	// todo later
	// FETCH_COMMUNITY_TASKS: 'FETCH_COMMUNITY_TASKS',
	// ADD_COMMUNITY_TASKS: 'ADD_COMMUNITY_TASKS',
	// RATE_COMMUNITY_TASK: 'RATE_COMMUNITY_TASK',
	// UPLOAD_TASK_TO_COMMUNITY: 'UPLOAD_TASK_TO_COMMUNITY',

	// admin only
	ADD_TASK: 'ADD_TASK',
	UPDATE_TASK: 'UPDATE_TASK',
	DELETE_TASK: 'DELETE_TASK',

	// no user interaction
	AUTO_SCHEDULE_TASK: 'AUTO_SCHEDULE_TASK',
	AUTO_REMOVE_SCHEDULED_TASKS: 'AUTO_REMOVE_SCHEDULED_TASKS',
	// is today a school day, a public holiday, a school holiday, etc.
	AUTO_SET_TODAYS_METADATA: 'AUTO_SET_TODAYS_METADATA',
	AUTO_ARCHIVE_ACTIVITIES: 'AUTO_ARCHIVE_ACTIVITIES',

	ADD_NEW_ACTIVITY: 'ADD_NEW_ACTIVITY', // AKA complete task
	COMPLETE_ACTIVITY: 'COMPLETE_ACTIVITY', // approver only
	ACKNOWLEDGE_ACTIVITY: 'ACKNOWLEDGE_ACTIVITY', // approver only
	ARCHIVE_ACTIVITY: 'ARCHIVE_ACTIVITY',
	UPDATE_ACTIVITY: 'UPDATE_ACTIVITY', // approver only
	DELETE_ARCHIVED_ACTIVITY: 'DELETE_ARCHIVED_ACTIVITY',

	ADD_USER: 'ADD_USER',
	UPDATE_USER: 'UPDATE_USER',
	DELETE_USER: 'DELETE_USER',
	ADD_USER_TO_TASK: 'ADD_USER_TO_TASK',

	UPDATE_HOUSEHOLD: 'UPDATE_HOUSEHOLD',

	ADD_MESSAGE: 'ADD_MESSAGE',
	DELETE_MESSAGE: 'DELETE_MESSAGE',
	USER_VIEWED_MESSAGE: 'USER_VIEWED_MESSAGE',
	USER_DISMISSED_MESSAGE: 'USER_DISMISSED_MESSAGE',

	PAY_USER: 'PAY_USER',
	UPDATE_ACCOUNT_LEDGER_ENTRY: 'UPDATE_ACCOUNT_LEDGER_ENTRY'
}

export const activityStatus = [
	'Not started',
	'In progress',
	'Complete',
	'Approved',
	'Archived'
];

export const scheduledItemStatus = [
	'Queued',
	'Active',
	'Overdue',
	'Expired',
	'Complete'
];

export const completionLevel = [
	'Not started',
	'Partially',
	'Fully',
	'Outstandingly'
];

export const interventionLevel = [
	'Volunteered',
	'Prompted',
	'Cajoled',
	'Battled'
];

export const ledgerEntryType = [
	'Credit',
	'Debit',
	'Correction'
];

export const messageType = [
	'Notice',
	'Error'
];

// export default constants;