export const constants = {
	// admin only
	ADD_TASK: 'ADD_TASK',
	UPDATE_TASK: 'UPDATE_TASK',
	DELETE_TASK: 'DELETE_TASK',
	VIEW_TASK: 'VIEW_TASK',
	LIST_ALL_TASKS: 'LIST_ALL_TASKS',
	UPDATE_PAY: 'UPDATE_PAY',
	UPDATE_CURRENCY: 'UPDATE_CURRENCY',
	UPDATE_ARCHIVE_ACTIVITIES_META: 'UPDATE_ARCHIVE_ACTIVITIES_META',
	UPDATE_COMPLETION_LEVEL_VALUES: 'UPDATE_COMPLETION_LEVEL_VALUES',
	UPDATE_INTERVENTION_LEVEL_VALUES: 'UPDATE_INTERVENTION_LEVEL_VALUES',

	ADD_PUBLIC_HOLIDAYS: 'ADD_PUBLIC_HOLIDAYS',
	UPDATE_PUBLIC_HOLIDAYS: 'ADD_PUBLIC_HOLIDAYS',
	ADD_SCHOOL_TERM: 'ADD_PUBLIC_HOLIDAYS',
	UPDATE_SCHOOL_TERM: 'ADD_PUBLIC_HOLIDAYS',

	// todo later
	// IMPORT_SCHOOL_TERMS: 'IMPORT_SCHOOL_TERMS',
	// LIST_SCHOOL_TERMS: 'LIST_SCHOOL_TERMS',
	// UPDATE_SCHOOL_TERM: 'UPDATE_SCHOOL_TERM',
	// IMPORT_PUBLIC_HOLIDAYS: 'IMPORT_PUBLIC_HOLIDAYS',
	// LIST_PUBLIC_HOLIDAYS: 'LIST_PUBLIC_HOLIDAYS',
	// UPDATE_PUBLIC_HOLIDAY: 'UPDATE_PUBLIC_HOLIDAY',
	// FETCH_COMMUNITY_TASKS: 'FETCH_COMMUNITY_TASKS',
	// LIST_COMMUNITY_TASKS: 'LIST_COMMUNITY_TASKS',
	// ADD_COMMUNITY_TASKS: 'ADD_COMMUNITY_TASKS',
	// RATE_COMMUNITY_TASK: 'RATE_COMMUNITY_TASK',
	// UPLOAD_TASK_TO_COMMUNITY: 'UPLOAD_TASK_TO_COMMUNITY',

	// no user interaction
	AUTO_SCHEDULE_TASK: 'AUTO_SCHEDULE_TASK',
	AUTO_REMOVE_SCHEDULED_TASKS: 'AUTO_REMOVE_SCHEDULED_TASKS',
	// is today a school day, a public holiday, a school holiday, etc.
	AUTO_SET_TODAYS_METADATA: 'AUTO_SET_TODAYS_METADATA',
	AUTO_ARCHIVE_ACTIVITIES: 'AUTO_ARCHIVE_ACTIVITIES',


	// user specific
	LIST_SCHEDULED_TASKS: 'LIST_SCHEDULED_TASKS',
	VIEW_SCHEDULED_TASK: 'VIEW_SCHEDULED_TASK',
	FILTER_SCHEDULED_TASKS: 'FILTER_SCHEDULED_TASKS',

	ADD_ACTIVITY: 'ADD_ACTIVITY', // AKA complete task
	UPDATE_ACTIVITY: 'UPDATE_APPROVED_ACTIVITY', // approver only
	ARCHIVE_ACTIVITY: 'ARCHIVE_ACTIVITY',
	DELETE_ARCHIVED_ACTIVITY: 'DELETE_ARCHIVED_ACTIVITY',
	LIST_ACTIVITIES: 'LIST_ACTIVITIES', // user specific
	FILTER_LISTED_ACTIVITIES: 'FILTER_LISTED_ACTIVITIES',

	// notify approver when a task activity needs to be reviewed and approved
	NOTIFY_APPROVER: 'NOTIFY_APPROVER',

	ADD_USER: 'ADD_USER',
	UPDATE_USER: 'UPDATE_USER',
	DELETE_USER: 'DELETE_USER',
	LIST_USERS: 'LIST_USERS',
	VIEW_USER: 'VIEW_USER', // owner or admin

	UPDATE_HOUSEHOLD: 'UPDATE_HOUSEHOLD',
	VIEW_HOUSEHOLD: 'VIEW_HOUSEHOLD',

	ADD_ERROR: 'ADD_ERROR',
	REMOVE_ERROR: 'REMOVE_ERROR',

	ADD_ACCOUNT_LEDGER_ENTRY: 'ADD_ACCOUNT_LEDGER_ENTRY'
}

export const activityStatus = [
	'In progress',
	'Complete',
	'Approved',
	'Archived'
];

export const scheduledItemStatus = [
	'Queued',
	'Active',
	'Overdue',
	'Expired',
	'Complete'
];
	


// export default constants;