const constants = {
	// admin only
	ADD_TASK: 'ADD_TASK',
	UPDATE_TASK: 'UPDATE_TASK',
	DELETE_TASK: 'DELETE_TASK',
	VIEW_TASK: 'VIEW_TASK',
	LIST_ALL_TASKS: 'LIST_ALL_TASKS',

	// no user interaction
	AUTO_SCHEDULE_TASK: 'AUTO_SCHEDULE_TASK',
	AUTO_REMOVE_SCHEDULED_TASKS: 'AUTO_REMOVE_SCHEDULED_TASKS',
	AUTO_SET_TODAYS_METADATA: 'AUTO_SET_TODAYS_METADATA',

	// user specific
	LIST_SCHEDULED_TASKS: 'LIST_SCHEDULED_TASKS',
	VIEW_SCHEDULED_TASK: 'VIEW_SCHEDULED_TASK',

	CREATE_ACTIVITY: 'CREATE_ACTIVITY', // AKA complete task
	APPROVE_ACTIVITY: 'APPROVE_ACTIVITY', // approver only
	UPDATE_APPROVED_ACTIVITY: 'UPDATE_APPROVED_ACTIVITY', // approver only
	LIST_ACTIVITIES: 'LIST_ACTIVITIES', // user specific

	// notify approver when a task activity needs to be reviewed and approved
	NOTIFY_APPROVER: 'NOTIFY_APPROVER',

	ADD_USER: 'ADD_USER',
	UPDATE_USER: 'UPDATE_USER',
	DELETE_USER: 'DELETE_USER',
	LIST_USERS: 'LIST_USERS',
	VIEW_USER: 'VIEW_USER', // owner or admin

	UPDATE_HOUSEHOLD: 'UPDATE_HOUSEHOLD',
	VIEW_HOUSEHOLD: 'VIEW_HOUSEHOLD',
	ADD_SCHOOL_TERM: 'ADD_SCHOOL_TERM',
	UPDATE_SCHOOL_TERM: 'UPDATE_SCHOOL_TERM',

	ADD_ERROR: 'ADD_ERROR',
	REMOVE_ERROR: 'REMOVE_ERROR'
}

export default constants;