const constants = {
	"CREATE_TASK": "CREATE_TASK",
	"UPDATE_TASK": "UPDATE_TASK",
	"CLONE_TASK": "CLONE_TASK",
	"DELETE_TASK": "DELETE_TASK",
	"VIEW_TASK": "VIEW_TASK",
	"LIST_TASKS": "LIST_TASKS",
	"ERROR_CREATE_TASK": "ERROR_CREATE_TASK",
	"ERROR_UPDATE_TASK": "ERROR_UPDATE_TASK",

	"CREATE_GOAL": "CREATE_GOAL",
	"UPDATE_GOAL": "UPDATE_GOAL",
	"CLONE_GOAL": "CLONE_GOAL",
	"DELETE_GOAL": "DELETE_GOAL",
	"VIEW_GOAL": "VIEW_GOAL",
	"LIST_GOALS": "LIST_GOALS",
	"ERROR_CREATE_GOAL": "ERROR_CREATE_GOAL",
	"ERROR_UPDATE_GOAL": "ERROR_UPDATE_GOAL",

	"ADD_TASK_TO_SCHEDULED": "ADD_TASK_TO_SCHEDULED",
	"REMOVE_TASK_FROM_SCHEDULED": "REMOVE_TASK_FROM_SCHEDULED",
	"ROTATE_RESPONSIBILIT_FOR_TASK": "ROTATE_RESPONSIBILIT_FOR_TASK",

	"CREATE_ACTIVITY": "CREATE_ACTIVITY",
	"APPROVE_ACTIVITY": "APPROVE_ACTIVITY",
	"VIEW_ACTIVITY": "VIEW_ACTIVITY",
	"LIST_ACTIVITY": "LIST_ACTIVITY",

	"ADD_USER": "ADD_USER",
	"UPDATE_USER": "UPDATE_USER",
	"DELETE_USER": "DELETE_USERS",
	"LIST_USERS": "LIST_USERS",
	"ERROR_ADD_USER": "ERROR_ADD_USER",
	"ERROR_UPDATE_USER": "ERROR_UPDATE_USER",

	"SHOW_POINTS": "SHOW_POINTS",

	"CREATE_HOUSEHOLD": "CREATE_HOUSEHOLD",
	"UPDATE_HOUSEHOLD": "UPDATE_HOUSEHOLD",
	"DELETE_HOUSEHOLD": "DELETE_HOUSEHOLD",
	"VIEW_HOUSEHOLD": "VIEW_HOUSEHOLD",
	"LIST_HOUSEHOLDS": "LIST_HOUSEHOLDS",
	"ERROR_CREATE_HOUSEHOLD": "ERROR_CREATE_HOUSEHOLD",
	"ERROR_UPDATE_HOUSEHOLD": "ERROR_UPDATE_HOUSEHOLD",

	"PAYMENT": "PAYMENT",
	"PAYMENT_ACKNOWLEGEMENT": "PAYMENT_ACKNOWLEGEMENT",
//	"PAYMENT_REJECTED": "PAYMENT_REJECTED"
};

export default constants;